import { test, expect, chromium } from "@playwright/test"
import { attach } from "./protocol"
import { spawn, execFileSync } from "node:child_process"
import { mkdir, rm, writeFile } from "node:fs/promises"
import { createInterface } from "node:readline"
import path from "node:path"

test("production comparison uses executed fixture history in the native panel", async ({}, testInfo) => {
  test.setTimeout(180000)
  const root = process.cwd()
  const evidence = path.join(root, testInfo.project.metadata.evidenceRoot ?? "evidence/WMLC-008/browser", "compare")
  const profile = path.join(evidence, "profile")
  await mkdir(evidence, { recursive: true })
  await rm(profile, { recursive: true, force: true })
  await mkdir(profile)
  const fixture = spawn("python3", ["-u", path.join(root, "tests/run-radar/native/browser_fixture.py"), path.join(profile, "synthetic.fifo")], { cwd: root, stdio: ["pipe", "pipe", "pipe"] })
  const lines = createInterface({ input: fixture.stdout })
  const stream = lines[Symbol.asyncIterator]()
  async function next() {
    const item = await stream.next()
    if (item.done) throw new Error("Follow fixture exited")
    return JSON.parse(item.value)
  }
  await next()
  async function mode(value: string) { fixture.stdin.write(JSON.stringify({ mode: value }) + "\n"); return next() }
  const extension = path.join(root, "build/chrome-mv3-prod")
  const context = await chromium.launchPersistentContext(profile, { channel: "chromium", headless: false, viewport: null,
    args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] })
  const observations: string[] = []
  try {
    const worker = context.serviceWorkers()[0] ?? await context.waitForEvent("serviceworker")
    const id = new URL(worker.url()).host
    const registration = path.join(profile, "NativeMessagingHosts")
    const install = (fifo: string) => execFileSync("python3", [path.join(root, "native/install.py"), "install", "--extension-id", id, "--fifo", fifo, "--directory", registration], { cwd: root })
    const remove = () => execFileSync("python3", [path.join(root, "native/install.py"), "remove", "--directory", registration], { cwd: root })
    install(path.join(profile, "synthetic.fifo"))
    const options = await context.newPage()
    await options.goto(`chrome-extension://${id}/options.html`)
    const request = (message: Record<string, unknown>) => options.evaluate(async value => await chrome.runtime.sendMessage(value), message)
    await mode("compare")
    const snapshot = await request({ type: "connection:connect", workspace: "fixture" })
    expect(snapshot.ok).toBe(true)
    const selection = { instance: snapshot.instance, workspace: "fixture", runId: snapshot.runs.find((run: { status: string; path: string }) => run.status === "failed" && run.path === "f/tests/compare").id }
    await mode("compare")
    const web = await context.newPage()
    await web.goto("about:blank")
    const browser = context.browser()!
    const session = await browser.newBrowserCDPSession()
    const target = async (page: string) => (await session.send("Target.getTargets")).targetInfos.find(info => info.url === `chrome-extension://${id}/${page}.html`)
    async function openPanel() {
      await worker.evaluate(async () => await chrome.action.openPopup())
      await expect.poll(async () => Boolean(await target("popup"))).toBe(true)
      const popupInfo = (await target("popup"))!
      const popup = await attach(session, popupInfo.targetId)
      await expect.poll(() => popup.evaluate('document.querySelectorAll(".run").length')).toBe(4)
      await popup.evaluate(`document.getElementById("run-${selection.runId}").click()`)
      await expect.poll(() => popup.evaluate('document.querySelector("[data-field=Logs] pre")?.textContent')).toContain("count must be positive")
      await popup.evaluate('Array.from(document.querySelectorAll("button")).find(button => button.textContent === "Continue in side panel").focus()')
      await popup.key("Enter", "Enter", 13)
      await expect.poll(async () => Boolean(await target("sidepanel"))).toBe(true)
      await session.send("Target.closeTarget", { targetId: popupInfo.targetId })
      return attach(session, (await target("sidepanel"))!.targetId)
    }
    let panel = await openPanel()
    const text = () => panel.evaluate('document.body.textContent')
    const compare = () => panel.evaluate('Array.from(document.querySelectorAll("button")).find(button => button.textContent === "Compare").click()')
    await expect.poll(text).toContain("Run completed")
    await compare()
    await expect.poll(text).toContain("Earlier success: 00000000-0000-0000-0000-000000000006")
    await expect.poll(text).toContain("Removed: removed")
    await expect.poll(text).toContain("Added: added")
    await expect.poll(text).toContain("Difference: 150 ms")
    await expect.poll(text).toContain("abc2")
    await expect.poll(text).toContain("count must be positive")
    expect(await panel.evaluate('document.querySelector(".comparison img, .comparison script") === null')).toBe(true)
    await panel.evaluate('document.querySelector(".comparison").scrollIntoView()')
    await panel.screenshot(path.join(evidence, "comparison.png"))
    observations.push("Actual toolbar popup and keyboard gesture open the native Chrome panel. Comparison chooses executed fixture success 6 instead of older success 1, displays both IDs and times, inputs, duration, version, result and logs. Untrusted input remains text.")
    const noBaseline = { ...selection, runId: "00000000-0000-0000-0000-000000000003" }
    await request({ type: "connection:select", selection: noBaseline })
    await expect.poll(text).toContain(noBaseline.runId)
    await expect.poll(text).toContain("Run completed")
    await compare()
    await expect.poll(text).toContain("No earlier success was returned")
    await panel.evaluate('document.querySelector(".comparison").scrollIntoView()')
    await panel.screenshot(path.join(evidence, "no-baseline.png"))
    observations.push("The actual failed no-baseline fixture execution shows an exhausted accessible-history state without invented values.")
    const numericReceipt = await mode("compare_numeric")
    expect(numericReceipt.fixtureExecutions.every((entry: { executed: boolean }) => entry.executed)).toBe(true)
    await request({ type: "connection:select", selection })
    await expect.poll(text).toContain(selection.runId)
    await expect.poll(text).toContain("Run completed")
    await compare()
    await expect.poll(text).toContain("Earlier success: 00000000-0000-0000-0000-000000000006")
    for (const label of ["Inputs", "Result"]) {
      const section = `Array.from(document.querySelectorAll(".comparison-field")).find(item => item.querySelector("h3")?.textContent === ${JSON.stringify(label)})`
      await expect.poll(() => panel.evaluate(`${section}.querySelector(".difference").textContent`)).toBe("Unsupported JSON numeric precision. Equality is unproven.")
      await panel.evaluate(`${section}.querySelectorAll("details").forEach(item => item.open = true)`)
      expect(await panel.evaluate(`${section}.textContent`)).toContain("9007199254740992")
      expect(await panel.evaluate(`${section}.textContent`)).toContain("9007199254740993")
    }
    await panel.evaluate('document.querySelector(".comparison").scrollIntoView()')
    await panel.screenshot(path.join(evidence, "numeric-precision.png"))
    await writeFile(path.join(evidence, "numeric-executions.json"), JSON.stringify(numericReceipt.fixtureExecutions, null, 2))
    observations.push("Executed numeric fixture success and failure retain distinct nested integers 9007199254740992 and 9007199254740993 in both inputs and results. Both field summaries report unsupported numeric precision and unproven equality. Expanded values retain the original digits.")
    const decimalReceipt = await mode("compare_decimal")
    expect(decimalReceipt.fixtureExecutions.every((entry: { executed: boolean }) => entry.executed)).toBe(true)
    await request({ type: "connection:select", selection: noBaseline })
    await expect.poll(text).toContain(noBaseline.runId)
    await request({ type: "connection:select", selection })
    await expect.poll(text).toContain(selection.runId)
    await expect.poll(text).toContain("Run completed")
    await compare()
    await expect.poll(text).toContain("Earlier success: 00000000-0000-0000-0000-000000000006")
    for (const label of ["Inputs", "Result"]) {
      const section = `Array.from(document.querySelectorAll(".comparison-field")).find(item => item.querySelector("h3")?.textContent === ${JSON.stringify(label)})`
      await expect.poll(() => panel.evaluate(`${section}.querySelector(".difference").textContent`)).toBe("Unsupported JSON numeric precision. Equality is unproven.")
      await panel.evaluate(`${section}.querySelectorAll("details").forEach(item => item.open = true)`)
      const content = String(await panel.evaluate(`${section}.textContent`))
      expect(content).toContain("1.00000000000000001")
      expect(content).toContain("1.0")
      expect(content.toLowerCase()).toContain("1e-400")
      await panel.evaluate(`${section}.scrollIntoView()`)
      await panel.screenshot(path.join(evidence, `decimal-${label.toLowerCase()}.png`))
    }
    await panel.evaluate('document.querySelector(".comparison").scrollIntoView()')
    await panel.screenshot(path.join(evidence, "decimal-precision.png"))
    await writeFile(path.join(evidence, "decimal-executions.json"), JSON.stringify(decimalReceipt.fixtureExecutions, null, 2))
    observations.push("Executed decimal identity workloads retain raw HTTP 1.0, 1.00000000000000001, and 1e-400 tokens through the native helper. Inputs and Result report unsupported numeric precision and unproven equality. Expanded values retain the original digits.")
    await mode("compare")
    await request({ type: "connection:select", selection: noBaseline })
    await expect.poll(text).toContain(noBaseline.runId)
    for (const [fixtureMode, expected] of [["compare_forbidden", "earlier success is forbidden"], ["compare_missing", "Unavailable metadata"], ["compare_large", "Large value"], ["compare_incompatible", "only top-level script and flow"], ["compare_limit", "Search limit reached"], ["compare_flow", "Flow version identifier"]]) {
      await mode(fixtureMode)
      await request({ type: "connection:select", selection })
      await expect.poll(text).toContain(selection.runId)
      await expect.poll(text).toContain("Run completed")
      await compare()
      await expect.poll(text).toContain(expected)
      await panel.evaluate('document.querySelector(".comparison").scrollIntoView()')
      await panel.screenshot(path.join(evidence, fixtureMode + ".png"))
      await mode("compare")
      await request({ type: "connection:select", selection: noBaseline })
      await expect.poll(text).toContain(noBaseline.runId)
    }
    await mode("compare_delay")
    await request({ type: "connection:select", selection })
    await expect.poll(text).toContain("Run completed")
    await compare()
    await expect.poll(text).toContain("Searching accessible")
    await request({ type: "connection:select", selection: noBaseline })
    await expect.poll(text).toContain(noBaseline.runId)
    await options.waitForTimeout(2300)
    expect(await text()).not.toContain("Earlier success:")
    observations.push("Forbidden baseline, missing fields, large values and incompatible job types show explicit states. A delayed history response cannot restore an old selection.")
    await mode("compare_delay")
    await request({ type: "connection:select", selection })
    await expect.poll(text).toContain("Run completed")
    await compare()
    await expect.poll(text).toContain("Searching accessible")
    await session.send("Target.closeTarget", { targetId: (await target("sidepanel"))!.targetId })
    await options.waitForTimeout(2400)
    const closed = (await mode("compare")).requests.length
    await options.waitForTimeout(2200)
    expect((await mode("compare")).requests.length).toBe(closed)
    panel = await openPanel()
    await expect.poll(text).toContain("Run completed")
    await compare()
    await expect.poll(text).toContain("Earlier success:")
    await request({ type: "connection:disconnect" })
    await expect.poll(text).toContain("Select a live run")
    expect(await options.evaluate(async () => await chrome.storage.local.get(null))).toEqual({ timezone: expect.any(String) })
    const receipt = await mode("compare")
    expect(receipt.fixtureExecutions.every((entry: { executed: boolean }) => entry.executed)).toBe(true)
    expect(receipt.requests.every((entry: { method: string }) => entry.method === "GET")).toBe(true)
    observations.push("Closing the panel cancels the comparison port. Disconnect clears identity and private state while retaining the timezone preference. Fixture workload executions include successful and failed outcomes. All fixture requests are GET requests.")
    remove()
    await writeFile(path.join(evidence, "browser.json"), JSON.stringify({ browserVersion: browser.version(), extensionId: id,
      manifest: await options.evaluate(() => chrome.runtime.getManifest()), syntheticJourneyProven: true, observations,
      fixtureExecutions: receipt.fixtureExecutions, fixtureRequests: receipt.requests, liveMutation: false }, null, 2))
  } finally {
    await context.close()
    fixture.stdin.end()
    await new Promise<void>(resolve => { if (fixture.exitCode !== null) resolve(); else { fixture.once("exit", () => resolve()); setTimeout(() => { fixture.kill(); resolve() }, 2000).unref() } })
    lines.close()
    await rm(profile, { recursive: true, force: true })
  }
})
