import { test, expect, chromium } from "@playwright/test"
import { spawn } from "node:child_process"
import { mkdir, rm, writeFile } from "node:fs/promises"
import { createInterface } from "node:readline"
import path from "node:path"
import { attach } from "./protocol"

test("password credentials use direct HTTP in the production toolbar and native panel", async ({}, testInfo) => {
  test.setTimeout(180000)
  const root = process.cwd(), evidence = path.join(root, testInfo.project.metadata.evidenceRoot)
  const profile = path.join(evidence, "profile")
  await mkdir(profile, { recursive: true })
  const fixture = spawn("python3", ["-u", path.join(root, "tests/run-radar/native/browser_fixture.py"), path.join(profile, "synthetic.fifo")], { cwd: root, stdio: ["pipe", "pipe", "pipe"] })
  const lines = createInterface({ input: fixture.stdout }), stream = lines[Symbol.asyncIterator]()
  async function next() {
    const item = await stream.next()
    if (item.done) throw new Error("Synthetic fixture exited")
    return JSON.parse(item.value)
  }
  const { port } = await next(), instance = `http://127.0.0.1:${port}`
  async function mode(value: string) { fixture.stdin.write(JSON.stringify({ mode: value }) + "\n"); return next() }
  const extension = path.join(root, "build/chrome-mv3-prod")
  const observations: string[] = []
  const launch = () => chromium.launchPersistentContext(profile, { channel: "chromium", headless: false, viewport: null,
    args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] })
  let context = await launch()
  try {
    const worker = context.serviceWorkers()[0] ?? await context.waitForEvent("serviceworker")
    const extensionId = new URL(worker.url()).host
    let options = await context.newPage()
    await options.goto(`chrome-extension://${extensionId}/options.html`)
    const request = (value: Record<string, unknown>) => options.evaluate(async message => await chrome.runtime.sendMessage(message), value)
    await options.getByLabel("Windmill base URL").fill(instance)
    await options.getByLabel("API key", { exact: true }).fill("synthetic-browser-credential")
    await options.getByLabel("Encryption password", { exact: true }).fill("synthetic-browser-password")
    await options.getByLabel("Confirm encryption password").fill("synthetic-browser-password")
    await options.getByRole("button", { name: "Save credentials" }).click()
    await expect(options.getByText("Saved credentials: Unlocked")).toBeVisible({ timeout: 60000 })
    expect(await options.evaluate(async () => {
      const local = JSON.stringify(await chrome.storage.local.get(null)), session = await chrome.storage.session.get(null)
      return { plaintextAbsent: !local.includes("synthetic-browser-credential") && !local.includes("synthetic-browser-password"),
        encrypted: !!((await chrome.storage.local.get("encryptedCredentials")).encryptedCredentials as { ciphertext?: string } | undefined)?.ciphertext, sessionUnlock: !!session.credentialUnlock,
        passwordCleared: !(document.getElementById("password") as HTMLInputElement).value, apiKeyCleared: !(document.getElementById("api-key") as HTMLInputElement).value }
    })).toEqual({ plaintextAbsent: true, encrypted: true, sessionUnlock: true, passwordCleared: true, apiKeyCleared: true })
    observations.push("Production settings save authenticated ciphertext and clear secret fields. Only session storage holds unlock material.")
    await expect(options.getByLabel("Encryption password", { exact: true })).toHaveAttribute("placeholder", "*******")
    await expect(options.getByLabel("Confirm encryption password")).toHaveCount(0)
    await options.getByRole("button", { name: "Replace credentials" }).click()
    await options.getByLabel("API key", { exact: true }).fill("discard-this-token")
    await options.getByRole("button", { name: "Cancel" }).click()
    await expect(options.getByLabel("API key", { exact: true })).toHaveValue("")
    await expect(options.getByLabel("Confirm encryption password")).toHaveCount(0)
    await options.getByRole("button", { name: "Replace credentials" }).click()
    await options.getByLabel("API key", { exact: true }).fill("synthetic-browser-credential")
    await options.getByLabel("Encryption password", { exact: true }).fill("synthetic-browser-password")
    await options.getByRole("button", { name: "Save replacement" }).click()
    await expect(options.getByRole("alert")).toHaveText("Passwords do not match.")
    await options.getByLabel("Confirm encryption password").fill("synthetic-browser-password")
    await options.getByRole("button", { name: "Save replacement" }).click()
    await expect(options.getByRole("alert")).toHaveCount(0)
    await expect(options.getByText("Saved credentials: Unlocked")).toBeVisible()
    observations.push("Saving and replacing require matching passwords. Settings explain that encryption persists while monitoring is unlocked and that there is no timed lock.")
    // Two options pages reproduce Connect while replacement awaits permission.
    const otherOptions = await context.newPage()
    await otherOptions.goto(`chrome-extension://${extensionId}/options.html`)
    await worker.evaluate(() => {
      const state = globalThis as typeof globalThis & { releasePermission?: () => void; permissionPaused?: boolean }
      const contains = chrome.permissions.contains.bind(chrome.permissions)
      chrome.permissions.contains = (async (permissions: chrome.permissions.Permissions) => {
        chrome.permissions.contains = contains
        state.permissionPaused = true
        await new Promise<void>(resolve => { state.releasePermission = resolve })
        return contains(permissions)
      }) as typeof chrome.permissions.contains
    })
    const replacing = request({ type: "credentials:replace", instance, apiKey: "synthetic-browser-credential", password: "synthetic-browser-password" })
    await expect.poll(() => worker.evaluate(() => (globalThis as typeof globalThis & { permissionPaused?: boolean }).permissionPaused)).toBe(true)
    const connecting = otherOptions.evaluate(async () => await chrome.runtime.sendMessage({ type: "connection:connect", workspace: "fixture" }))
    await otherOptions.waitForTimeout(100)
    await worker.evaluate(() => {
      const state = globalThis as typeof globalThis & { releasePermission?: () => void; permissionPaused?: boolean }
      state.releasePermission!()
      delete state.releasePermission
      delete state.permissionPaused
    })
    expect(await replacing).toMatchObject({ ok: true, instance, saved: true })
    expect(await connecting).toEqual({ ok: false, code: "request_canceled" })
    expect(await request({ type: "connection:get" })).toEqual({ ok: true, connection: null })
    await otherOptions.close()
    observations.push("Connect from a second options page during paused replacement is canceled. Replacement cannot restore the old connection.")
    await expect(options.getByRole("button", { name: "Test connection" })).toBeVisible()
    await options.setViewportSize({ width: 320, height: 720 })
    expect(await options.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await options.setViewportSize({ width: 1200, height: 900 })
    const connectionBox = await options.getByRole("region", { name: "Connect Windmill" }).boundingBox()
    const workspaceBox = await options.getByRole("region", { name: "Workspace and monitoring" }).boundingBox()
    expect(connectionBox).not.toBeNull()
    expect(workspaceBox).not.toBeNull()
    expect(workspaceBox!.x).toBeGreaterThan(connectionBox!.x + connectionBox!.width)
    expect(workspaceBox!.y).toBe(connectionBox!.y)
    observations.push("Wide settings use adjacent connection and workspace columns. A 320-pixel window has no horizontal overflow.")
    await options.screenshot({ path: path.join(evidence, "settings.png"), fullPage: true })
    await options.getByRole("button", { name: "Load workspaces" }).click()
    await expect(options.getByRole("combobox")).toHaveValue("fixture")
    await options.getByRole("button", { name: /^Connect$/ }).click()
    await expect(options.getByRole("status")).toContainText("5 recent runs")
    const browser = context.browser()
    if (!browser) throw new Error("Missing production browser")
    const session = await browser.newBrowserCDPSession()
    const web = await context.newPage(); await web.goto("about:blank"); await web.bringToFront()
    await worker.evaluate(async () => await chrome.action.openPopup())
    async function target(page: string) {
      return (await session.send("Target.getTargets")).targetInfos.find(info => info.url === `chrome-extension://${extensionId}/${page}.html`)
    }
    await expect.poll(async () => Boolean(await target("popup"))).toBe(true)
    const popupTarget = await target("popup")
    if (!popupTarget) throw new Error("Missing toolbar popup")
    const popup = await attach(session, popupTarget.targetId)
    await expect.poll(() => popup.evaluate('document.querySelectorAll(".run").length')).toBe(5)
    expect(await popup.evaluate('({width:innerWidth,height:innerHeight})')).toEqual({ width: 380, height: 572 })
    await popup.screenshot(path.join(evidence, "toolbar.png"))
    await popup.evaluate('document.getElementById("run-00000000-0000-0000-0000-000000000002").click()')
    await expect.poll(() => popup.evaluate('document.body.textContent')).toContain("Result")
    await popup.evaluate('Array.from(document.querySelectorAll("button")).find(button => button.textContent === "Continue in side panel").focus()')
    await popup.key("Enter", "Enter", 13)
    await expect.poll(async () => Boolean(await target("sidepanel"))).toBe(true)
    const panelTarget = await target("sidepanel")
    if (!panelTarget) throw new Error("Missing native side panel")
    const panel = await attach(session, panelTarget.targetId)
    await expect.poll(() => panel.evaluate('document.body.textContent')).toContain("Result")
    observations.push("Actual 380 by 572 toolbar popup loads five direct-HTTP runs and opens inspection in the native side panel without a helper.")
    await session.send("Target.closeTarget", { targetId: popupTarget.targetId })
    const selection = { instance, workspace: "fixture", runId: "00000000-0000-0000-0000-000000000003" }
    await mode("follow_start")
    expect(await request({ type: "connection:select", selection })).toEqual({ ok: true })
    const logs = () => panel.evaluate('document.querySelector("[data-field=Logs] pre")?.textContent')
    await expect.poll(logs).toBe("starté\npar")
    await mode("follow_progress")
    await expect.poll(logs, { timeout: 10000 }).toBe("starté\npartial line\nstep-a done\n")
    await mode("follow_complete")
    await expect.poll(logs, { timeout: 10000 }).toBe("starté\npartial line\nstep-a done\nfinished\n")
    await expect.poll(() => panel.evaluate('document.querySelector("[data-field=Result] pre")?.textContent')).toContain('"finished": true')
    observations.push("Direct HTTP follow receives fragmented UTF-8 snapshots, growing logs, terminal status, and final results in the native panel.")
    await mode("compare_decimal")
    const comparisonRuns = await request({ type: "connection:refresh" })
    const failed = comparisonRuns.runs.find((run: { status: string; path: string }) => run.status === "failed" && run.path === "f/tests/compare")
    expect(failed).toBeTruthy()
    expect(await request({ type: "connection:select", selection: { ...selection, runId: failed.id } })).toEqual({ ok: true })
    await expect.poll(() => panel.evaluate('document.body.textContent')).toContain("Run completed")
    await panel.evaluate('Array.from(document.querySelectorAll("button")).find(button => button.textContent === "Compare").click()')
    await expect.poll(() => panel.evaluate('document.body.textContent')).toContain("Earlier success: 00000000-0000-0000-0000-000000000006")
    await expect.poll(() => panel.evaluate('document.body.textContent')).toContain("Unsupported JSON numeric precision")
    expect(await panel.evaluate('document.body.textContent')).toContain("1.00000000000000001")
    observations.push("Direct HTTP comparison chooses the executed earlier success and preserves decimal tokens without claiming rounded JSON equality.")
    await mode("workspace_normal")
    await request({ type: "connection:refresh" })
    await request({ type: "connection:pin", selection })
    expect((await request({ type: "connection:pins" })).pins).toEqual([selection])
    await request({ type: "connection:switch", workspace: "second" })
    expect((await request({ type: "connection:pins" })).pins).toEqual([])
    await request({ type: "connection:switch", workspace: "fixture" })
    expect((await request({ type: "connection:pins" })).pins).toEqual([selection])
    await mode("workspace_failed")
    await request({ type: "connection:refresh" })
    expect(await worker.evaluate(async () => await chrome.action.getBadgeText({}))).toBe("1")
    observations.push("Direct HTTP workspace switches preserve scoped pins. An observed active-to-failed transition updates the unseen-failure badge.")
    await options.bringToFront()
    await options.getByRole("button", { name: /^Lock$/ }).click()
    await expect(options.getByText("Saved credentials: Locked")).toBeVisible()
    await expect(options.getByLabel("Confirm encryption password")).toHaveCount(0)
    await expect(options.getByRole("button", { name: "Replace credentials" })).toBeDisabled()
    await expect(options.getByText(/There is no automatic time limit/)).toBeVisible()
    await options.screenshot({ path: path.join(evidence, "locked-settings.png"), fullPage: true })
    expect(await request({ type: "connection:refresh" })).toEqual({ ok: false, code: "credentials_locked" })
    expect(await worker.evaluate(async () => await chrome.action.getBadgeText({}))).toBe("LOCK")
    await options.getByLabel("Enter password to unlock").fill("wrong-password-only")
    await options.getByRole("button", { name: /^Unlock$/ }).click()
    await expect(options.getByRole("alert")).toContainText("password is incorrect")
    await options.getByLabel("Enter password to unlock").fill("synthetic-browser-password")
    await options.getByRole("button", { name: /^Unlock$/ }).click()
    await expect(options.getByText("Saved credentials: Unlocked")).toBeVisible()
    await expect(options.getByLabel("Confirm encryption password")).toHaveCount(0)
    await expect(options.getByLabel("Encryption password", { exact: true })).toHaveAttribute("placeholder", "*******")
    await options.screenshot({ path: path.join(evidence, "unlocked-settings.png"), fullPage: true })
    observations.push("Unlocked credentials show fixed masks without confirmation. Replacement opens explicitly and Cancel clears the form. Locked credentials show Enter password to unlock.")
    expect((await request({ type: "connection:refresh" })).ok).toBe(true)
    const workerTarget = (await session.send("Target.getTargets")).targetInfos.find(info => info.type === "service_worker" && info.url === worker.url())
    if (!workerTarget) throw new Error("Missing production worker target")
    await session.send("Target.closeTarget", { targetId: workerTarget.targetId })
    expect((await request({ type: "connection:refresh" })).ok).toBe(true)
    observations.push("Lock pauses direct requests and shows LOCK. Wrong passwords fail. Unlock resumes requests and survives worker suspension.")
    await context.close()
    context = await launch()
    options = await context.newPage()
    await options.goto(`chrome-extension://${extensionId}/options.html`)
    await expect(options.getByText("Saved credentials: Locked")).toBeVisible()
    expect(await request({ type: "connection:refresh" })).toEqual({ ok: false, code: "credentials_locked" })
    expect(await request({ type: "credentials:get" })).toMatchObject({ saved: true, locked: true })
    await options.getByRole("button", { name: "Remove credentials" }).click()
    await expect(options.getByText("Saved credentials: None")).toBeVisible()
    expect(await options.evaluate(async () => Object.keys(await chrome.storage.local.get(null)))).toEqual(["timezone"])
    observations.push("Actual Chrome restart locks persistent ciphertext. Remove clears credential and private scope state while preserving timezone.")
    await writeFile(path.join(evidence, "browser.json"), JSON.stringify({ fixtureOnly: true, liveProven: false, observations }, null, 2))
  } finally {
    await context.close()
    fixture.stdin.end(); fixture.kill("SIGTERM"); lines.close()
    await rm(profile, { recursive: true, force: true })
  }
})
