import { test, expect, chromium } from "@playwright/test"
import { spawn } from "node:child_process"
import { mkdir, rm, writeFile } from "node:fs/promises"
import { createInterface } from "node:readline"
import path from "node:path"
import { attach } from "./protocol"

test("script and flow catalog and older history work in the production toolbar", async ({}, testInfo) => {
  test.setTimeout(120000)
  const root = process.cwd(), evidence = path.join(root, testInfo.project.metadata.evidenceRoot), profile = path.join(evidence, "profile")
  await mkdir(profile, { recursive: true })
  const fixture = spawn("python3", ["-u", path.join(root, "tests/run-radar/native/browser_fixture.py"), path.join(profile, "synthetic.fifo")], { cwd: root, stdio: ["pipe", "pipe", "pipe"] })
  const lines = createInterface({ input: fixture.stdout }), stream = lines[Symbol.asyncIterator]()
  async function next() { const item = await stream.next(); if (item.done) throw new Error("Synthetic fixture exited"); return JSON.parse(item.value) }
  const { port } = await next(), instance = `http://127.0.0.1:${port}`
  async function mode(value: string) { fixture.stdin.write(JSON.stringify({ mode: value }) + "\n"); return next() }
  await mode("history")
  const extension = path.join(root, "build/chrome-mv3-prod")
  const context = await chromium.launchPersistentContext(profile, { channel: "chromium", headless: false, viewport: null,
    args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] })
  const observations: string[] = []
  try {
    const worker = context.serviceWorkers()[0] ?? await context.waitForEvent("serviceworker"), extensionId = new URL(worker.url()).host
    const options = await context.newPage(); await options.goto(`chrome-extension://${extensionId}/options.html`)
    await options.getByLabel("Windmill base URL").fill(instance)
    await options.getByLabel("API key", { exact: true }).fill("synthetic-browser-credential")
    await options.getByLabel("Encryption password", { exact: true }).fill("synthetic-browser-password")
    await options.getByLabel("Confirm encryption password").fill("synthetic-browser-password")
    await options.getByRole("button", { name: "Save credentials" }).click()
    await expect(options.getByText("Saved credentials: Unlocked")).toBeVisible({ timeout: 60000 })
    await options.getByRole("button", { name: "Load workspaces" }).click()
    await expect(options.getByRole("combobox")).toHaveValue("fixture")
    await options.getByRole("button", { name: /^Connect$/ }).click()
    await expect(options.getByRole("status")).toContainText("100 recent runs")
    const browser = context.browser(); if (!browser) throw new Error("Missing production browser")
    const session = await browser.newBrowserCDPSession(), web = await context.newPage()
    await web.goto("about:blank"); await web.bringToFront(); await worker.evaluate(async () => await chrome.action.openPopup())
    const target = async (name: string) => (await session.send("Target.getTargets")).targetInfos.find(info => info.url === `chrome-extension://${extensionId}/${name}.html`)
    await expect.poll(async () => Boolean(await target("popup"))).toBe(true)
    const popupTarget = await target("popup"); if (!popupTarget) throw new Error("Missing toolbar popup")
    const popup = await attach(session, popupTarget.targetId)
    const text = () => popup.evaluate("document.body.textContent")
    const click = (label: string) => popup.evaluate(`Array.from(document.querySelectorAll('button')).find(button => button.textContent === ${JSON.stringify(label)}).click()`)
    await expect.poll(() => popup.evaluate("document.querySelectorAll('.run').length")).toBe(100)
    const before = await worker.evaluate(async () => JSON.stringify((await chrome.storage.local.get("monitoring")).monitoring))
    await click("Find scripts and flows")
    await expect.poll(text).toContain("Catalog complete: 202 scripts and flows")
    await popup.evaluate("const input=document.querySelector('input[type=search]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'payroll'); input.dispatchEvent(new Event('input',{bubbles:true}))")
    await expect.poll(() => popup.evaluate("document.querySelectorAll('.run').length")).toBe(2)
    await expect.poll(text).toContain("Catalog complete: 202 scripts and flows")
    await popup.evaluate("Array.from(document.querySelectorAll('.run')).find(button => button.querySelector('.kind-pill').textContent === 'Flow').click()")
    await expect.poll(text).toContain("Flow: f/tests/old")
    await expect.poll(() => popup.evaluate("document.querySelectorAll('.run').length")).toBe(100)
    await click("Older")
    await expect.poll(text).toContain("Page 2")
    await expect.poll(() => popup.evaluate("document.querySelectorAll('.run').length")).toBe(1)
    await expect.poll(text).toContain("Final page")
    expect(await popup.evaluate("Array.from(document.querySelectorAll('button')).find(button=>button.textContent==='Older').disabled")).toBe(true)
    expect(await popup.evaluate("({width:innerWidth,height:innerHeight,overflow:document.documentElement.scrollWidth>innerWidth})")).toEqual({ width: 380, height: 572, overflow: false })
    await popup.screenshot(path.join(evidence, "older-history.png"))
    await popup.evaluate("document.querySelector('.pin').click()")
    await expect.poll(() => popup.evaluate("document.querySelector('.pin').textContent")).toBe("Unpin")
    await popup.evaluate("document.querySelector('.run').click()")
    await expect.poll(text).toContain("history fixture logs")
    await popup.evaluate("Array.from(document.querySelectorAll('button')).find(button=>button.textContent==='Continue in side panel').focus()")
    await popup.key("Enter", "Enter", 13)
    await expect.poll(async () => Boolean(await target("sidepanel"))).toBe(true)
    const panelTarget = await target("sidepanel"); if (!panelTarget) throw new Error("Missing native side panel")
    const panel = await attach(session, panelTarget.targetId)
    await expect.poll(() => panel.evaluate("document.body.textContent")).toContain("history fixture logs")
    expect(await worker.evaluate(async () => JSON.stringify((await chrome.storage.local.get("monitoring")).monitoring))).toBe(before)
    observations.push("The actual 380 by 572 toolbar discovers a flow absent from recent workspace runs on catalog page 2 by summary. Exact-path history supports older pages, pins, inspection, and the native side panel. History leaves monitoring unchanged.")
    await session.send("Target.closeTarget", { targetId: popupTarget.targetId })
    await web.bringToFront(); await worker.evaluate(async () => await chrome.action.openPopup())
    await expect.poll(async () => Boolean(await target("popup"))).toBe(true)
    const reopenedTarget = await target("popup"); if (!reopenedTarget) throw new Error("Missing reopened popup")
    const reopened = await attach(session, reopenedTarget.targetId)
    const clickAgain = (label: string) => reopened.evaluate(`Array.from(document.querySelectorAll('button')).find(button => button.textContent === ${JSON.stringify(label)}).click()`)
    await expect.poll(() => reopened.evaluate("document.querySelectorAll('.run').length")).toBe(100)
    expect(await reopened.evaluate("Array.from(document.querySelectorAll('.kind-pill'), node => node.textContent).includes('Script')")).toBe(true)
    expect(await reopened.evaluate("Array.from(document.querySelectorAll('.kind-pill'), node => node.textContent).includes('Other')")).toBe(true)
    expect(await reopened.evaluate("Array.from(document.querySelectorAll('.kind-pill'), node => node.textContent).includes('Unknown')")).toBe(true)
    const delayStartCount = (await mode("history_delay")).requests.length
    await clickAgain("Find scripts and flows")
    await expect.poll(() => reopened.evaluate("document.body.textContent")).toContain("Catalog complete: 202 scripts and flows")
    await reopened.evaluate("Array.from(document.querySelectorAll('.run')).find(button => button.querySelector('.kind-pill').textContent === 'Flow' && button.textContent.includes('Old payroll')).click()")
    await expect.poll(() => reopened.evaluate("document.body.textContent")).toContain("Loading history...")
    await expect.poll(async () => {
      const state = await mode("history_delay")
      return state.requests.slice(delayStartCount).some((request: { delayedHistory?: boolean }) => request.delayedHistory === true)
    }).toBe(true)
    await clickAgain("Find scripts and flows")
    await expect.poll(() => reopened.evaluate("document.body.textContent")).toContain("Catalog complete: 202 scripts and flows")
    await reopened.evaluate("const input=document.querySelector('input[type=search]'); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'payroll'); input.dispatchEvent(new Event('input',{bubbles:true}))")
    await expect.poll(() => reopened.evaluate("document.querySelectorAll('.run').length")).toBe(2)
    await reopened.evaluate("Array.from(document.querySelectorAll('.run')).find(button => button.querySelector('.kind-pill').textContent === 'Script').click()")
    await expect.poll(() => reopened.evaluate("document.body.textContent")).toContain("Script: f/tests/old")
    await expect.poll(() => reopened.evaluate("document.querySelectorAll('.run').length")).toBe(100)
    expect(await reopened.evaluate("Array.from(document.querySelectorAll('.run .kind-pill')).every(node => node.textContent === 'Script')")).toBe(true)
    await new Promise(resolve => setTimeout(resolve, 2200))
    expect(await reopened.evaluate("document.body.textContent")).toContain("Script: f/tests/old")
    expect(await reopened.evaluate("Array.from(document.querySelectorAll('.run .kind-pill')).every(node => node.textContent === 'Script')")).toBe(true)
    await mode("history")
    await clickAgain("Older")
    await expect.poll(() => reopened.evaluate("document.querySelectorAll('.run').length")).toBe(1)
    expect(await reopened.evaluate("document.querySelector('.run').textContent")).toContain("000000001101")
    await reopened.evaluate("document.querySelector('.pin').click()")
    await expect.poll(() => reopened.evaluate("document.querySelector('.pin').textContent")).toBe("Unpin")
    await reopened.screenshot(path.join(evidence, "script-history.png"))
    await reopened.evaluate("document.querySelector('.run').click()")
    await expect.poll(() => reopened.evaluate("document.body.textContent")).toContain("history fixture logs")
    expect(await reopened.evaluate("document.querySelector('.kind-pill').textContent")).toBe("Script")
    await reopened.evaluate("Array.from(document.querySelectorAll('button')).find(button=>button.textContent==='Continue in side panel').focus()")
    await reopened.key("Enter", "Enter", 13)
    await expect.poll(() => panel.evaluate("document.querySelector('.kind-pill')?.textContent")).toBe("Script")
    await expect.poll(() => panel.evaluate("document.body.textContent")).toContain("000000001101")
    await panel.screenshot(path.join(evidence, "script-panel.png"))
    observations.push("The toolbar keeps equal Script and Flow paths selectable. Script history uses its kind on both pages, supports a pin, and opens script inspection in the native side panel. A delayed flow response cannot replace equal-path script history. Recent runs label preview as Other and absent metadata as Unknown.")
    await clickAgain("Back")
    await clickAgain("Workspace history")
    await expect.poll(() => reopened.evaluate("document.querySelectorAll('.run').length")).toBe(100)
    await clickAgain("Older")
    await expect.poll(() => reopened.evaluate("document.querySelectorAll('.run').length")).toBe(1)
    await clickAgain("Newer")
    await expect.poll(() => reopened.evaluate("document.querySelectorAll('.run').length")).toBe(100)
    await mode("history_failure"); await clickAgain("Older")
    await expect.poll(() => reopened.evaluate("document.body.textContent")).toContain("History unavailable")
    await mode("history"); await clickAgain("Try again")
    await expect.poll(() => reopened.evaluate("document.querySelectorAll('.run').length")).toBe(1)
    observations.push("Workspace history supports older and newer pages. A server error clears rows and retry recovers the same page.")
    await writeFile(path.join(evidence, "observations.json"), JSON.stringify({ ok: true, observations }, null, 2) + "\n")
  } finally {
    await context.close(); lines.close(); fixture.stdin.end(); fixture.kill("SIGTERM"); await rm(profile, { recursive: true, force: true })
  }
})
