import React from "react"
import { afterEach, beforeEach, it, expect, vi } from "vitest"
import { act, cleanup, render, screen } from "@testing-library/react"
import userEvent from "@testing-library/user-event"
import Options from "../../src/options"
import { recovery } from "../../src/connection"

const responses = vi.fn()
const sendMessage = vi.fn((message: { type: string }) => message.type === "credentials:get" ? Promise.resolve({ ok: true, saved: false, locked: false, instance: null }) : responses(message))
beforeEach(() => { vi.stubGlobal("chrome", { runtime: { id: "a".repeat(32), sendMessage }, permissions: { request: vi.fn(async () => true) } }); responses.mockReset(); sendMessage.mockClear() })
afterEach(() => { cleanup(); vi.unstubAllGlobals() })

it("shows the public instance and accessible workspace and connects with masked credential fields", async () => {
  responses.mockResolvedValueOnce({ ok: true, instance: "https://fixture.example", workspaces: ["fixture"] })
    .mockResolvedValueOnce({ ok: true, connection: null })
    .mockResolvedValueOnce({ ok: true, mode: "live", instance: "https://fixture.example", workspace: "fixture", snapshotAt: "2026-10-03T18:30:00.000Z", runs: [] })
    .mockResolvedValueOnce({ ok: true, connection: null })
  const user = userEvent.setup()
  render(<Options />)
  await user.click(screen.getByRole("button", { name: "Load workspaces" }))
  await screen.findByText("https://fixture.example")
  expect(screen.getByRole("combobox")).toBeTruthy()
  expect(screen.getByRole("textbox", { name: "Fallback timezone" })).toBeTruthy()
  expect(screen.getByLabelText("API key").getAttribute("type")).toBe("password")
  await user.click(screen.getByRole("button", { name: /^Connect$/ }))
  await screen.findByText(/Connected to fixture/)
  expect(sendMessage).toHaveBeenLastCalledWith({ type: "connection:connect", workspace: "fixture" })
  await user.click(screen.getByRole("button", { name: "Disconnect" }))
  await screen.findByText(/Private caches are cleared/)
})

it.each(Object.entries(recovery))("shows a recovery action for %s", async (code, message) => {
  responses.mockResolvedValue({ ok: false, code })
  const user = userEvent.setup()
  render(<Options />)
  await user.click(screen.getByRole("button", { name: "Test helper" }))
  expect((await screen.findByRole("alert")).textContent).toBe(message)
})

it("allows disconnect during an active request and ignores its late reply", async () => {
  let reply: (value: unknown) => void = () => { throw new Error("Missing request") }
  responses.mockImplementationOnce(() => new Promise(resolve => { reply = resolve })).mockResolvedValueOnce({ ok: true, connection: null })
  const user = userEvent.setup()
  render(<Options />)
  await user.click(screen.getByRole("button", { name: "Test helper" }))
  await user.click(screen.getByRole("button", { name: "Disconnect" }))
  await screen.findByText(/Private caches are cleared/)
  await act(async () => reply({ ok: true, instance: "https://fixture.example", helper: "installed" }))
  expect(screen.queryByText("https://fixture.example")).toBeNull()
})

it("rejects invalid timezone input and reports save failures before recovery", async () => {
  const user = userEvent.setup()
  render(<Options />)
  const input = screen.getByRole("textbox", { name: "Fallback timezone" })
  await user.clear(input)
  await user.type(input, "Not/A_Zone")
  await user.click(screen.getByRole("button", { name: "Save timezone" }))
  expect((await screen.findByRole("alert")).textContent).toContain("valid named timezone")
  expect(responses).not.toHaveBeenCalled()
  await user.clear(input)
  await user.type(input, "Asia/Kathmandu")
  responses.mockResolvedValueOnce({ ok: false, code: "helper_failure" })
  await user.click(screen.getByRole("button", { name: "Save timezone" }))
  expect((await screen.findByRole("alert")).textContent).toBe(recovery.helper_failure)
  responses.mockResolvedValueOnce({ ok: true, timezone: "Asia/Kathmandu" })
  await user.click(screen.getByRole("button", { name: "Save timezone" }))
  await screen.findByText(/Timezone saved/)
  expect(sendMessage).toHaveBeenLastCalledWith({ type: "connection:timezone-save", timezone: "Asia/Kathmandu" })
})

it("saves through a narrow permission gesture and clears the secret fields", async () => {
  responses.mockResolvedValue({ ok: true, saved: true, locked: false, instance: "https://fixture.example" })
  const user = userEvent.setup()
  render(<Options />)
  await user.type(screen.getByLabelText("Windmill base URL"), "https://fixture.example/")
  await user.type(screen.getByLabelText("API key"), "synthetic-settings-token")
  await user.type(screen.getByLabelText("Encryption password", { exact: true }), "synthetic-password-only")
  await user.type(screen.getByLabelText("Confirm encryption password"), "synthetic-password-only")
  await user.click(screen.getByRole("button", { name: "Save credentials" }))
  await screen.findByText("Saved credentials: Unlocked")
  expect(screen.getByRole("button", { name: "Test connection" })).toBeTruthy()
  expect(chrome.permissions.request).toHaveBeenCalledWith({ origins: ["https://fixture.example/*"] })
  expect(responses).toHaveBeenLastCalledWith({ type: "credentials:save", instance: "https://fixture.example", apiKey: "synthetic-settings-token", password: "synthetic-password-only" })
  expect(screen.queryByLabelText("Confirm encryption password")).toBeNull()
  for (const name of ["API key", "Encryption password"]) expect((screen.getByLabelText(name, { exact: true }) as HTMLInputElement).value).toBe("")
  responses.mockResolvedValue({ ok: true, saved: true, locked: true, instance: "https://fixture.example" })
  await user.click(screen.getByRole("button", { name: /^Lock$/ }))
  await screen.findByText("Saved credentials: Locked")
  expect(screen.queryByLabelText("Confirm encryption password")).toBeNull()
  expect((screen.getByRole("button", { name: "Replace credentials" }) as HTMLButtonElement).disabled).toBe(true)
  expect(screen.getByText(/There is no automatic time limit/)).toBeTruthy()
  expect(screen.getByText(/saved API key stays encrypted even while unlocked/)).toBeTruthy()
  await user.type(screen.getByLabelText("Enter password to unlock"), "synthetic-password-only")
  responses.mockResolvedValue({ ok: true, saved: true, locked: false, instance: "https://fixture.example" })
  await user.click(screen.getByRole("button", { name: /^Unlock$/ }))
  await screen.findByText("Saved credentials: Unlocked")
  expect(responses).toHaveBeenLastCalledWith({ type: "credentials:unlock", password: "synthetic-password-only" })
  expect(screen.queryByLabelText("Confirm encryption password")).toBeNull()
  expect(screen.getByLabelText("Encryption password", { exact: true }).getAttribute("placeholder")).toBe("*******")
  await user.click(screen.getByRole("button", { name: "Replace credentials" }))
  await user.type(screen.getByLabelText("API key"), "discard-this-token")
  await user.type(screen.getByLabelText("Windmill base URL"), "/discard")
  await user.click(screen.getByRole("button", { name: "Cancel" }))
  expect((screen.getByLabelText("Windmill base URL") as HTMLInputElement).value).toBe("https://fixture.example")
  expect((screen.getByLabelText("API key") as HTMLInputElement).value).toBe("")
  expect(screen.queryByLabelText("Confirm encryption password")).toBeNull()
  expect(responses).toHaveBeenLastCalledWith({ type: "credentials:unlock", password: "synthetic-password-only" })
  await user.click(screen.getByRole("button", { name: "Replace credentials" }))
  await user.type(screen.getByLabelText("API key"), "synthetic-replacement-token")
  await user.type(screen.getByLabelText("Encryption password", { exact: true }), "synthetic-new-password")
  await user.click(screen.getByRole("button", { name: "Save replacement" }))
  await screen.findByText("Passwords do not match.")
  expect(responses).toHaveBeenLastCalledWith({ type: "credentials:unlock", password: "synthetic-password-only" })
  await user.type(screen.getByLabelText("Confirm encryption password"), "synthetic-new-password")
  await user.click(screen.getByRole("button", { name: "Save replacement" }))
  await screen.findByText("Saved credentials: Unlocked")
  expect(responses).toHaveBeenLastCalledWith({ type: "credentials:replace", instance: "https://fixture.example", apiKey: "synthetic-replacement-token", password: "synthetic-new-password" })
  responses.mockResolvedValue({ ok: true, saved: false, locked: false, instance: null })
  await user.click(screen.getByRole("button", { name: "Remove credentials" }))
  await screen.findByText("Saved credentials: None")
})

it("rejects mismatched passwords and permission denial without a credential write", async () => {
  const user = userEvent.setup()
  render(<Options />)
  await user.type(screen.getByLabelText("Windmill base URL"), "https://fixture.example")
  await user.type(screen.getByLabelText("API key"), "synthetic-settings-token")
  await user.type(screen.getByLabelText("Encryption password", { exact: true }), "synthetic-password-only")
  await user.click(screen.getByRole("button", { name: "Save credentials" }))
  await screen.findByText("Passwords do not match.")
  expect(chrome.permissions.request).not.toHaveBeenCalled()
  await user.type(screen.getByLabelText("Confirm encryption password"), "synthetic-password-only")
  const permissionMock = chrome.permissions.request as unknown as ReturnType<typeof vi.fn>
  permissionMock.mockResolvedValue(false)
  await user.click(screen.getByRole("button", { name: "Save credentials" }))
  await screen.findByText(recovery.permission_denied)
  expect(responses).not.toHaveBeenCalled()
  expect((screen.getByLabelText("API key") as HTMLInputElement).value).toBe("")
})

it("shows saved masks when the unlocked configuration page reopens", async () => {
  sendMessage.mockImplementationOnce(async () => ({ ok: true, saved: true, locked: false, instance: "https://fixture.example" }))
  render(<Options />)
  await screen.findByText("Saved credentials: Unlocked")
  expect(screen.getByText("Connection saved. ChroMill is unlocked.")).toBeTruthy()
  expect(screen.queryByLabelText("Confirm encryption password")).toBeNull()
  for (const name of ["API key", "Encryption password"]) {
    const input = screen.getByLabelText(name, { exact: true }) as HTMLInputElement
    expect(input.value).toBe("")
    expect(input.placeholder).toBe("*******")
    expect(input.readOnly).toBe(true)
  }
})
